version: '3.1'

services:

  api:
    image: moulaye07/api
    command: bash -c "tail -F anything"
    ports:
      - 8001:8001
    depends_on:
      - mongo

  front:
    image: moulaye07/client
    command: bash -c "tail -F anything"
    ports:
      - 3000:3000
    depends_on:
      - api

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/
  
  mosquitto:
    image: moulaye07/mosquitto
    command: bash -c "service mosquitto start;tail -F anything"
    ports:
      - 1883:1883
   
  police:
    image: moulaye07/police
    build:
      context: ./police
    command: bash -c "tail -F anything"
    depends_on:
      - api
      - mosquitto
   
  hopital:
    image: moulaye07/hopital
    build:
      context: ./hopital
    command: bash -c "tail -F anything"
    depends_on:
      - api
      - mosquitto
  
  listener:
    image: moulaye07/listener
    build:
      context: ./listener
    command: bash -c "tail -F anything"
    depends_on:
      - api
      - mosquitto
  
