const appActions = {
  SET_STATIONS: "SET_STATIONS",
  REMOVE_STATIONS: "REMOVE_STATIONS",
  SET_SELECTED_STATION: "SET_SELECTED_STATION",
  REMOVE_SELECTED_STATION: "REMOVE_SELECTED_STATION",
  SET_CURRENT_STATION_STATISTICS: "SET_CURRENT_STATION_STATISTICS",
  REMOVE_CURRENT_STATION_STATISTICS: "REMOVE_CURRENT_STATION_STATISTICS",
  SET_SELECTED_DATE: "SET_SELECTED_DATE",
  REMOVE_SELECTED_DATE: "REMOVE_SELECTED_DATE",
  SET_ACCIDENT_DETAILS: "SET_ACCIDENT_DETAILS",
  SET_SELECTED_ACCIDENT: "SET_SELECTED_ACCIDENT",
  SET_SELECTED_STATION_ACCIDENTS: "SET_SELECTED_STATION_ACCIDENTS",
  SET_PERSON: "SET_PERSON",
  SET_RIGHT_SECTION_TAP: "SET_RIGHT_SECTION_TAP",
};
export default appActions;
